### ISSUE TITLE
关于"E2E"这个参数

### ISSUE THREAD

**Issue by Banyueqin** [liuheng92/OCR_EVALUATION#1]
您好，当我使用　python2.7 script.py -g gt.zip -s submit.zip -p '{"LTRB":true,"E2E":false}'　来评测检测的时候，会报错：Error!
Line in sample not valid. Sample: 1 Line: 38,43,920,215,Tiredness Error: Format incorrect. Should be: xmin,ymin,xmax,ymax
但是我的"E2E"的参数是false,为什么这样不行呢

**Comment by MichaelHL-ai** [comment]
E2E设置为true即可，因为你的样本有文本结果
