### ISSUE TITLE
将四边形左边转为矩形的代码中存在一个小BUG。

### ISSUE THREAD

**Issue by iLoveTangY** [liuheng92/OCR_EVALUATION#2]
[Algorithm_DetEva.py](https://github.com/liuheng92/OCR_EVALUATION/blob/master/Algorithm_DetEva.py#L196-L197)第196行应该是
```python
ymin = points_y[np.argmin(points_y)]
```

**Comment by MichaelHL-ai** [comment]
恩，是的，谢谢提醒
