### ISSUE TITLE
python script.py 报错

### ISSUE THREAD

**Issue by uceclz0** [liuheng92/OCR_EVALUATION#3]
您好，我用的是unix，conda创建的python2.7虚拟环境，ide是vscode。当时输入python script.py -g gt.zip -s submit.zip -p '{"LTRB":true, "E2E":true}'报错 unrecognized arguments: -g gt.zip -s submit.zip.
请问如何解决  此外我在rrc_evaluation_funcs中更改了LTRB和E2E为true, 命令行输入python script.py -g gt.zip -s submit.zip， 报错‘float’ object is not callable。谢谢

**Comment by wqtwjt1996** [comment]
我也有這樣的問題。。

**Comment by uceclz0** [comment]
> 我也有這樣的問題。。

调试了好久还是解决不了。换个模型吧。请问下你，这个作者提供的gt和result里面四个点分别是代表左上右下 还是左下右上的坐标?

**Comment by cyLVlyl** [comment]
请问你解决了吗 @uceclz0

**Comment by cyLVlyl** [comment]
@uceclz0 应该是复制黏贴的问题  重新打一遍就行了
